/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.NhanVien;
import connect.ConnectToSQL;
import java.sql.Connection;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuananh
 */
public class JPanelFormQLNhanVien extends javax.swing.JPanel {
    ConnectToSQL sql = new ConnectToSQL();
    private final String DB_URL = sql.DB_URL;
    private final String USER_NAME = sql.USER_NAME;
    private final String PASSWORD = sql.PASSWORD;
    private Connection conn;
    private Statement stmt;
    private final ArrayList<NhanVien> dsnv = new ArrayList<>();
    /**
     * Creates new form JPanelFormQLNhanVien
     */
    public JPanelFormQLNhanVien() {
        initComponents();
        getDanhSanhKhachHang();
        HienThiDanhSachKhachHang(dsnv);
    }
    private void getDanhSanhKhachHang(){
        try {
            // connnect to database 'phones'
            conn = getConnection(DB_URL, USER_NAME, PASSWORD);
            // crate statement
            stmt = conn.createStatement();
            // get data from table 'hoa don'
            ResultSet rs = stmt.executeQuery("select * from NhanVien");
            // show data
            while (rs.next()) {
                NhanVien nv = new NhanVien();
                nv.setMaNV(rs.getString(1));
                nv.setTenNV(rs.getString(2));
                nv.setGioitinh(rs.getString(4));
                nv.setDiaChi(rs.getString(5));
                nv.setEmail(rs.getString(7));
                nv.setSdt(rs.getString(6));
                nv.setLuong(Integer.parseInt(rs.getString(3)));
                nv.setMaCV(rs.getString(8));
                dsnv.add(nv);
            }
            // close connection
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void HienThiDanhSachKhachHang(ArrayList<NhanVien> dsnv) {
        try {
            // show data
            DefaultTableModel tblModel = null;
            String header[] = {"ID", "Tên Nhân Viên", "Giới tính","Chức Vụ", "Địa Chỉ", "SDT", "Email", "Lương"};
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            for (NhanVien nv : dsnv) {
                data = new Vector();
                data.add(nv.getMaNV());
                data.add(nv.getTenNV());
                data.add(nv.getGioitinh());
                data.add(setChucVu(nv.getMaCV()));
             
                data.add(nv.getSdt());
                data.add(nv.getEmail());
                data.add(nv.getLuong());
                tblModel.addRow(data);
            }
            tblNhanvien.setModel(tblModel);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private String setChucVu(String maCV){
        switch(maCV.trim()){
            case "BH":
                return "Bán Hàng";
            case "BV":
                return "Bảo Vệ";
            case "KT":
                return "Kế Toán";
            case "QL":
                return "Quản Lý";
            default:
                return "";
        }
    }
    private String setMaCV(String cv){
        switch(cv){
            case "Bán Hàng":
                return "BH";
            case "Bảo Vệ":
                return "BV";
            case "Kế Toán":
                return "KT";
            case "Quản Lý":
                return "QL";
            default:
                return "";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtManhanvien = new javax.swing.JTextField();
        txtTennhanvien = new javax.swing.JTextField();
        cbxGioitinh = new javax.swing.JComboBox<>();
        cbxChucvu = new javax.swing.JComboBox<>();
        txtLuong = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapnhap = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXuatfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxAll = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");
        add(jLabel1);
        jLabel1.setBounds(335, 6, 380, 29);

        txtManhanvien.setName("txtManhanvien"); // NOI18N
        add(txtManhanvien);
        txtManhanvien.setBounds(210, 100, 160, 20);

        txtTennhanvien.setName("txtTennhanvien"); // NOI18N
        add(txtTennhanvien);
        txtTennhanvien.setBounds(210, 140, 160, 20);

        cbxGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbxGioitinh.setName("cbxGioitinh"); // NOI18N
        add(cbxGioitinh);
        cbxGioitinh.setBounds(210, 180, 160, 20);

        cbxChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bán Hàng", "Bảo Vệ", "Kế Toán", "Quản Lý" }));
        cbxChucvu.setName("cbxChucvu"); // NOI18N
        add(cbxChucvu);
        cbxChucvu.setBounds(210, 220, 160, 20);

        txtLuong.setName("txtLuong"); // NOI18N
        add(txtLuong);
        txtLuong.setBounds(510, 220, 160, 20);

        txtEmail.setName("txtEmail"); // NOI18N
        add(txtEmail);
        txtEmail.setBounds(510, 180, 160, 20);

        txtSDT.setName("txtSDT"); // NOI18N
        add(txtSDT);
        txtSDT.setBounds(510, 140, 160, 20);

        txtDiachi.setName("txtDiachi"); // NOI18N
        add(txtDiachi);
        txtDiachi.setBounds(510, 100, 160, 20);

        btnThem.setText("Thêm");
        btnThem.setName("btnThem"); // NOI18N
        add(btnThem);
        btnThem.setBounds(700, 100, 90, 23);

        btnCapnhap.setText("Cập Nhập");
        btnCapnhap.setName("btnCapnhap"); // NOI18N
        add(btnCapnhap);
        btnCapnhap.setBounds(700, 140, 90, 23);

        btnXoa.setText("Xóa");
        btnXoa.setName("btnXoa"); // NOI18N
        add(btnXoa);
        btnXoa.setBounds(700, 180, 90, 23);

        btnXuatfile.setText("Xuất File");
        btnXuatfile.setName("btnXuatfile"); // NOI18N
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });
        add(btnXuatfile);
        btnXuatfile.setBounds(700, 220, 90, 23);

        jLabel2.setText("Mã Nhân Viên");
        add(jLabel2);
        jLabel2.setBounds(130, 100, 80, 20);

        jLabel4.setText("Tên Nhân Viên");
        add(jLabel4);
        jLabel4.setBounds(130, 140, 80, 20);

        jLabel3.setText("Giới Tinh");
        add(jLabel3);
        jLabel3.setBounds(130, 180, 80, 20);

        jLabel6.setText("Chức Vụ");
        add(jLabel6);
        jLabel6.setBounds(130, 220, 80, 20);

        jLabel7.setText("Địa Chỉ");
        add(jLabel7);
        jLabel7.setBounds(460, 100, 50, 20);

        jLabel8.setText("SDT");
        add(jLabel8);
        jLabel8.setBounds(460, 140, 50, 20);

        jLabel9.setText("Email");
        add(jLabel9);
        jLabel9.setBounds(460, 180, 50, 20);

        jLabel5.setText("Lương");
        add(jLabel5);
        jLabel5.setBounds(460, 220, 50, 20);

        cbxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Bán Hàng", "Bảo Vệ", "Kế Toán", "Quản Lý" }));
        cbxAll.setName("cbxAll"); // NOI18N
        add(cbxAll);
        cbxAll.setBounds(170, 290, 90, 25);

        btnLoc.setText("Lọc");
        btnLoc.setToolTipText("");
        btnLoc.setName("btnLoc"); // NOI18N
        add(btnLoc);
        btnLoc.setBounds(100, 290, 70, 25);

        txtTimkiem.setText("Nhập tên nhân viên cần tìm");
        txtTimkiem.setName("txtTimkiem"); // NOI18N
        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });
        add(txtTimkiem);
        txtTimkiem.setBounds(370, 290, 230, 25);

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setToolTipText("");
        btnTimkiem.setName("btnTimkiem"); // NOI18N
        add(btnTimkiem);
        btnTimkiem.setBounds(600, 290, 90, 25);

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nhân Viên", "Giới Tính", "Chức Vụ", "Địa Chỉ", "SĐT", "Email", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblNhanvien.setName("tblNhanvien"); // NOI18N
        jScrollPane1.setViewportView(tblNhanvien);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 330, 820, 240);
    }// </editor-fold>//GEN-END:initComponents
     private void HienThiChiTiet(int selectedIndex) {
        txtManhanvien.setText(dsnv.get(selectedIndex).getMaNV());
        txtTennhanvien.setText(dsnv.get(selectedIndex).getTenNV());
        cbxGioitinh.setSelectedItem(dsnv.get(selectedIndex).getGioitinh());
        cbxChucvu.setSelectedItem(dsnv.get(selectedIndex).getMaCV());
        txtSDT.setText(dsnv.get(selectedIndex).getSdt());
        txtEmail.setText(dsnv.get(selectedIndex).getEmail());
        txtLuong.setText(dsnv.get(selectedIndex).getLuong()+"");
    }
     private void ThemNV(){
        String maNV = txtManhanvien.getText();
        String tenNV=txtTennhanvien.getText();
        String gioiTinh = (String) cbxGioitinh.getSelectedItem();
        String chucVu =(String) cbxChucvu.getSelectedItem();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        String luong = txtLuong.getText();

        NhanVien nv = new NhanVien();
        if (dsnv.contains(nv)) {
                JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                nv = new NhanVien();
                dsnv.add(nv);
                try {
                    conn = getConnection(DB_URL, USER_NAME, PASSWORD);
                    stmt = conn.createStatement();
                    // Them dữ liệu cho bảng khách hàng
                    String sql="insert into NhanVien values('" + maNV + "'" + ",N'" + tenNV + "',N'" + gioiTinh + "',N'" + chucVu + "','" + sdt + "','" + email + "','"+ luong +"'')";
                    stmt.executeUpdate(sql);
                    conn.close();
                } catch (Exception ex) {
                    Logger.getLogger(JPanelFormQLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        HienThiDanhSachKhachHang(dsnv);
    }
     private void HienThiTimKiem(String maNV) {
        ArrayList<NhanVien> dstknv = new ArrayList<>();
        for (NhanVien nv : dstknv) {
            if (maNV.equalsIgnoreCase(nv.getMaNV().trim())) {
                dstknv.add(nv);
                break;
            }
        }
        HienThiDanhSachKhachHang(dstknv);
    }
      private void XoaNhanVien(String maNV) {
        for (NhanVien hd : dsnv) {
            if (maNV.equals(hd.getMaNV())) {
                dsnv.remove(hd);
                break;
            }
        }
    }
       //xóa hóa đơn khỏi csdl
    private void XoaNhanVienCSDL(String maNV) {
        try {
            // connnect to database 'testdb'
            conn = getConnection(DB_URL, USER_NAME, PASSWORD);
            // crate statement
            stmt = conn.createStatement();
            String strSql = "delete from ChiTietHoaDon where MaHD='" + maNV +"'";
            stmt.executeUpdate(strSql);
            strSql = "delete from HoaDon where MaHD='" + maNV +"'";
            stmt.executeUpdate(strSql);
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
       private void ClearTextbox() {
        txtManhanvien.setText("");
        txtTennhanvien.setText("");
        cbxGioitinh.setSelectedItem("");
        cbxChucvu.setSelectedItem("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtLuong.setText("");
        txtManhanvien.requestFocus(true);
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String id = txtTimkiem.getText();
        if (id.equals("")) {
            HienThiDanhSachKhachHang(dsnv);
        } else {
            HienThiTimKiem(id);
        }
    }                                          
    
    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
        txtTimkiem.setText("");
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXuatfileActionPerformed
    private void tblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int selectedIndex = tblNhanvien.getSelectedRow();
        HienThiChiTiet(selectedIndex);
    }  
     private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String id = txtManhanvien.getText();
        XoaNhanVien(id);
        ClearTextbox();
        HienThiDanhSachKhachHang(dsnv);
        XoaNhanVienCSDL(id);
    }       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhap;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JComboBox<String> cbxAll;
    private javax.swing.JComboBox<String> cbxChucvu;
    private javax.swing.JComboBox<String> cbxGioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtManhanvien;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTennhanvien;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
