/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.sql.*;
import static java.sql.DriverManager.getConnection;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuananh
 */
public class JPaneFormQLHoaDon extends javax.swing.JPanel {

    private static String DB_URL = "jdbc:sqlserver://localhost:1433;"
            + "databaseName=Phones;"
            + "integratedSecurity=true";
    private static String USER_NAME = "tuananh";
    private static String PASSWORD = "";

    /**
     * Creates new form JPaneFormQLHoaDonl
     */
    public JPaneFormQLHoaDon() {
        initComponents();
        try {
            // connnect to database 'testdb'
            Connection conn = getConnection(DB_URL, USER_NAME, PASSWORD);
            // crate statement
            Statement stmt = conn.createStatement();
            // get data from table 'tai khoan'
            ResultSet rs = stmt.executeQuery("select MaHD,NgayLap,HoaDon.MaNV,TenNV,HoaDon.MaKH,TenKH from HoaDon "
                    + "inner join KhachHang on HoaDon.MaKH = KhachHang.MaKH "
                    + "inner join NhanVien on HoaDon.MaNV = NhanVien.MaNV");
            // show data
            DefaultTableModel tblModel = null;
            String header[] = {"ID", "Ngày Lập", "Mã Nhân Viên", "Tên Nhân Viên", "Mã Khách Hàng", "Tên Khách Hàng", ""};
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString(1));
                data.add(rs.getString(2));
                data.add(rs.getString(3));
                data.add(rs.getString(4));
                data.add(rs.getString(5));
                data.add(rs.getString(6));
                data.add("");
                tblModel.addRow(data);
//                jTableHoaDon.add(rs.getString(0),rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),"chi tiet");
            }
            jTableHoaDon.setModel(tblModel);
            // close connection
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtNgaylap = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHoaDon = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtMaKhachHang = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        btnXuatHoaDon = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnLoc = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Hóa Đơn");
        add(jLabel1);
        jLabel1.setBounds(335, 6, 250, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn ");
        add(jLabel2);
        jLabel2.setBounds(10, 60, 120, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ngày Lập");
        add(jLabel3);
        jLabel3.setBounds(10, 100, 83, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mã Nhân Viên");
        add(jLabel4);
        jLabel4.setBounds(10, 140, 126, 22);

        txtMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMaHoaDon);
        txtMaHoaDon.setBounds(150, 60, 190, 28);

        txtNgaylap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtNgaylap);
        txtNgaylap.setBounds(150, 100, 190, 28);

        txtMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMaNhanVien);
        txtMaNhanVien.setBounds(150, 140, 190, 28);

        jTableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ngày Lập", "Mã Nhân Viên", "Tên Nhân Viên", "Mã Khách Hàng", "Tên Khách Hàng", "Thêm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableHoaDon);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 262, 900, 340);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tên Nhân Viên");
        add(jLabel5);
        jLabel5.setBounds(350, 60, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mã Khách Hàng");
        add(jLabel6);
        jLabel6.setBounds(350, 100, 150, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tên Khách Hàng");
        add(jLabel7);
        jLabel7.setBounds(350, 140, 150, 22);

        txtTenNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtTenNhanVien);
        txtTenNhanVien.setBounds(510, 60, 190, 28);

        txtMaKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMaKhachHang);
        txtMaKhachHang.setBounds(510, 100, 190, 28);

        txtTenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtTenKhachHang);
        txtTenKhachHang.setBounds(510, 140, 190, 28);

        btnXuatHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        add(btnXuatHoaDon);
        btnXuatHoaDon.setBounds(720, 60, 160, 31);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        add(btnXoa);
        btnXoa.setBounds(720, 100, 160, 31);

        btnXuatFile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXuatFile.setText("Xuất File");
        add(btnXuatFile);
        btnXuatFile.setBounds(720, 140, 160, 31);

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        add(btnTimKiem);
        btnTimKiem.setBounds(410, 230, 117, 27);

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTim.setText("Nhập mã hóa đơn cần tìm");
        txtTim.setToolTipText("");
        add(txtTim);
        txtTim.setBounds(240, 230, 170, 27);

        btnLoc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLoc.setText("Lọc");
        add(btnLoc);
        btnLoc.setBounds(160, 230, 80, 27);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        add(jFormattedTextField1);
        jFormattedTextField1.setBounds(10, 230, 150, 27);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHoaDon;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgaylap;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
