/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.DienThoai;
import java.util.*;
import connect.ConnectToSQL;
import java.sql.Connection;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;
import java.util.logging.Level;


/**
 *
 * @author tuananh
 */
public class JpanelFormQLDienThoai extends javax.swing.JPanel {

    ConnectToSQL sql = new ConnectToSQL();
    private final String DB_URL = sql.DB_URL;
    private final String USER_NAME = sql.USER_NAME;
    private final String PASSWORD = sql.PASSWORD;
    private Connection conn;
    private Statement stmt;
    private final ArrayList<DienThoai> dsdt = new ArrayList<>();

    /**
     * Creates new form JpanelFormQLDienThoai
     */
    public JpanelFormQLDienThoai() {
        initComponents();
        getDanhSanhDienThoai();
        HienThiDanhSachDienThoai(dsdt);        
    }

    //Lấy ds từ CSDL vào mảng
    private void getDanhSanhDienThoai(){
        try {
            // connnect to database 'phones'
            conn = getConnection(DB_URL, USER_NAME, PASSWORD);
            // crate statement
            stmt = conn.createStatement();
            // get data from table 'hoa don'
            ResultSet rs = stmt.executeQuery("select * from DienThoai ");
            // show data
            while (rs.next()) {
                DienThoai dt = new DienThoai();
                dt.setMaDT(rs.getString(1));
                dt.setMaHangSX(rs.getString(2));
                dt.setTenDT(rs.getString(3));
                dt.setSoLuong(Integer.parseInt(rs.getString(4)));
                dt.setGiaBan(Integer.parseInt(rs.getString(5)));
                dt.setRam(Integer.parseInt(rs.getString(6)));
                dt.setRom(Integer.parseInt(rs.getString(7)));
                dt.setMaKho(rs.getString(8));
                dsdt.add(dt);
            }
            // close connection
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    //Hiện thị ds điện thoại ra bảng
    private void HienThiDanhSachDienThoai(ArrayList<DienThoai> dsdt) {
        try {
            // show data
            DefaultTableModel tblModel = null;
            String header[] = {"ID", "Hãng Sản Xuất", "Tên Điện Thoại", "Số Lượng", "Gia Bán", "Ram", "Rom","Kho"};
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            for (DienThoai dt : dsdt) {
                data = new Vector();
                data.add(dt.getMaDT());
                data.add(setHangSX(dt.getMaHangSX()));
                data.add(dt.getTenDT());
                data.add(dt.getSoLuong());
                data.add(dt.getGiaBan());
                data.add(dt.getRam());
                data.add(dt.getRom());
                data.add(dt.getMaKho());
                tblModel.addRow(data);
            }
            tblDienThoai.setModel(tblModel);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private String setHangSX(String maHangSX){
        switch(maHangSX.trim()){
            case "AP":
                return "Apple";
            case "SS":
                return "SamSung";
            case "SO":
                return "Sony";
            case "NO":
                return "Nokia";
            case "LG":
                return "LG";
            case "XI":
                return "Xiaomi";
            case "VI":
                return "Vivo";
            case "OP":
                return "Oppo";
            default:
                return "";
        }
    }
    private String setMaHangSX(String hangSX){
        switch(hangSX){
            case "Apple":
                return "AP";
            case "SamSung":
                return "SS";
            case "Sony":
                return "SO";
            case "Nokia":
                return "NO";
            case "LG":
                return "LG";
            case "Xiaomi":
                return "XI";
            case "Vivo":
                return "VI";
            case "Oppo":
                return "OP";
            default:
                return "";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Click vào bảng thì hiển thị dữ liệu trên textbox
    private void HienThiChiTietDT (int selectedIndex){
        txtMaDT.setText(dsdt.get(selectedIndex).getMaDT());
        setHangSX(dsdt.get(selectedIndex).getMaHangSX());
        txtTenDT.setText(dsdt.get(selectedIndex).getTenDT());
        txtSoLuong.setText(dsdt.get(selectedIndex).getSoLuong()+"");
        txtGiaBan.setText(dsdt.get(selectedIndex).getGiaBan()+"");
        txtRam.setText(dsdt.get(selectedIndex).getRam()+"");
        txtRom.setText(dsdt.get(selectedIndex).getRom()+"");
        cbxKho.addItem(dsdt.get(selectedIndex).getMaKho());
        
    }
    
    //hien thi danh sach tim kiem len bang
    private void HienThiTimKiem(String MaDT) {
        ArrayList<DienThoai> dstkDT = new ArrayList<>();
        for (DienThoai dt : dsdt) {
            if (MaDT.equalsIgnoreCase(dt.getMaDT().trim())) {
                dstkDT.add(dt);
                break;
            }
        }
        HienThiDanhSachDienThoai(dstkDT);
    }
    
    //Xóa điện thoại khỏi mảng
    private void XoaDienThoai(String MaDT){
        for (DienThoai dt : dsdt) {
            if (MaDT.equals(dt.getMaDT())) {
                dsdt.remove(dt);
                break;
            }
        }
    }
    
   //Xóa điện thoại khỏi CSDL
      private void XoaDienThoaiCSDL(String MaDT) {
        try {
            // connnect to database 'testdb'
            conn = getConnection(DB_URL, USER_NAME, PASSWORD);
            // crate statement
            stmt = conn.createStatement();
            String strSql = "delete from DienThoai where MaDT='" + MaDT +"'";
            stmt.executeUpdate(strSql);
            strSql = "delete from HoaDon where MaDT='" + MaDT +"'";
            stmt.executeUpdate(strSql);
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
      
    //clear textbox
    private void ClearTextbox() {
        txtMaDT.setText("");
        cbxHang.addItem("");
        txtTenDT.setText("");
        txtSoLuong.setText("");
        txtGiaBan.setText("");
        txtRam.setText("");
        txtRom.setText("");
        cbxKho.addItem("");
        txtMaDT.requestFocus(true);
    }
    
    @SuppressWarnings("unchecked")
     //sự liện click vào bảng
    private void jTableDienThoaiMouseClicked(java.awt.event.MouseEvent evt) {                                          
        int selectedIndex = tblDienThoai.getSelectedRow();
        HienThiChiTietDT(selectedIndex);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        txtSoLuong = new javax.swing.JTextField();
        txtTenDT = new javax.swing.JTextField();
        cbxHang = new javax.swing.JComboBox<>();
        txtMaDT = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        cbxKho = new javax.swing.JComboBox<>();
        txtRom = new javax.swing.JTextField();
        txtRam = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnThemDienThoai = new java.awt.Button();
        btnCN = new java.awt.Button();
        btnXoa = new java.awt.Button();
        btnXuat = new java.awt.Button();
        btnTimKiem = new java.awt.Button();
        txtTimKiem = new javax.swing.JTextField();
        cbxLoc = new javax.swing.JComboBox<>();
        btnLoc = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDienThoai = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(900, 600));
        setLayout(null);

        label1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label1.setText("Mã Điện Thoại");
        add(label1);
        label1.setBounds(20, 60, 90, 21);

        label2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label2.setText("Hãng Sản Xuất");
        add(label2);
        label2.setBounds(20, 90, 90, 21);

        label3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label3.setText("Tên Điện Thoại");
        add(label3);
        label3.setBounds(20, 120, 100, 21);

        label4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label4.setText("Số Lượng");
        add(label4);
        label4.setBounds(20, 150, 70, 21);

        txtSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSoLuong.setName("txtSoLuong"); // NOI18N
        add(txtSoLuong);
        txtSoLuong.setBounds(130, 150, 170, 23);

        txtTenDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTenDT.setName("txtTenDT"); // NOI18N
        add(txtTenDT);
        txtTenDT.setBounds(130, 120, 170, 23);

        cbxHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "SamSung", "Sony", "Nokia", "LG", "Xiaomi", "ViVo", "Oppo" }));
        cbxHang.setName("cbxHang"); // NOI18N
        add(cbxHang);
        cbxHang.setBounds(130, 90, 170, 23);

        txtMaDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMaDT.setName("txtMaDT"); // NOI18N
        add(txtMaDT);
        txtMaDT.setBounds(130, 60, 170, 23);

        label5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label5.setText("Giá bán");
        add(label5);
        label5.setBounds(390, 60, 50, 21);

        label6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label6.setText("Ram");
        add(label6);
        label6.setBounds(390, 90, 31, 21);

        label7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label7.setText("Rom");
        add(label7);
        label7.setBounds(390, 120, 32, 21);

        label8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label8.setText("Kho");
        add(label8);
        label8.setBounds(390, 150, 29, 21);

        cbxKho.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KHO_001", "KHO_002" }));
        cbxKho.setName("cbxKho"); // NOI18N
        cbxKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhoActionPerformed(evt);
            }
        });
        add(cbxKho);
        cbxKho.setBounds(470, 150, 160, 23);

        txtRom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRom.setName("txtRom"); // NOI18N
        add(txtRom);
        txtRom.setBounds(470, 120, 160, 23);

        txtRam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRam.setName("txtRam"); // NOI18N
        add(txtRam);
        txtRam.setBounds(470, 90, 160, 23);

        txtGiaBan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtGiaBan.setName("txtGia"); // NOI18N
        add(txtGiaBan);
        txtGiaBan.setBounds(470, 60, 160, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Quản Lý Điện Thoại");
        add(jLabel2);
        jLabel2.setBounds(335, 6, 250, 29);

        btnThemDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThemDienThoai.setLabel("Thêm");
        btnThemDienThoai.setName("btnThem"); // NOI18N
        btnThemDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDienThoaiActionPerformed(evt);
            }
        });
        add(btnThemDienThoai);
        btnThemDienThoai.setBounds(740, 60, 70, 20);

        btnCN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCN.setLabel("Cập nhật");
        btnCN.setName("btnCN"); // NOI18N
        btnCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNActionPerformed(evt);
            }
        });
        add(btnCN);
        btnCN.setBounds(740, 90, 70, 20);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXoa.setLabel("Xóa");
        btnXoa.setName("btnXoa"); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(740, 120, 70, 20);

        btnXuat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXuat.setLabel("Xuất File");
        btnXuat.setName("btnXuat"); // NOI18N
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });
        add(btnXuat);
        btnXuat.setBounds(740, 150, 70, 20);

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem.setLabel("Tìm Kiếm");
        btnTimKiem.setName("btnTimKiem"); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem);
        btnTimKiem.setBounds(510, 200, 80, 20);

        txtTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTimKiem.setText("Nhập tên điện thoại cần tìm kiếm");
        txtTimKiem.setFocusCycleRoot(true);
        txtTimKiem.setName("txtTimKiem"); // NOI18N
        add(txtTimKiem);
        txtTimKiem.setBounds(280, 200, 220, 20);

        cbxLoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Apple", "SamSung", "Sony", "Nokia", "LG", "Xiaomi", "ViVo", "Oppo" }));
        cbxLoc.setName("cbxLoc"); // NOI18N
        add(cbxLoc);
        cbxLoc.setBounds(100, 200, 160, 20);

        btnLoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLoc.setLabel("Lọc");
        btnLoc.setName("btnLoc"); // NOI18N
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });
        add(btnLoc);
        btnLoc.setBounds(20, 200, 70, 20);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tblDienThoai.setBackground(new java.awt.Color(240, 240, 240));
        tblDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblDienThoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Hãng Sản Xuất", "Tên Điện Thoại", "Số Lượng", "Giá Bán", "Ram", "Rom", "Mã Kho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDienThoai.setName("tblDienThoai"); // NOI18N
        jScrollPane1.setViewportView(tblDienThoai);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 860, 350);
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void btnThemDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDienThoaiActionPerformed
        String MaDT = txtMaDT.getText();
        String Hang = (String) cbxHang.getSelectedItem();
        String tenDT = txtTenDT.getText();
        String sl = txtSoLuong.getText();
        String giaban = txtGiaBan.getText();
        String ram = txtRam.getText();
        String rom = txtRom.getText();
        String kho = (String)cbxKho.getSelectedItem();
        DienThoai dt = new DienThoai();
        if (dsdt.contains(dt)) {
            JOptionPane.showMessageDialog(null, "Điện thoại này đã tồn tại", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            dt = new DienThoai();
            dsdt.add(dt);
            try {
                conn = getConnection(DB_URL, USER_NAME, PASSWORD);
                stmt = conn.createStatement();
                // Them dữ liệu cho bảng DienThoai
                String sql="insert into DienThoai values('" + MaDT + "'" + ",N'" + Hang + "',N'" + tenDT + "','" + sl + "','" + giaban + "','" + ram + "', '" + kho + "')";
                stmt.executeUpdate(sql);
                conn.close();
            } catch (Exception ex) {
                Logger.getLogger(JpanelFormQLDienThoai.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        HienThiDanhSachDienThoai(dsdt);
        
        
    }//GEN-LAST:event_btnThemDienThoaiActionPerformed

    private void cbxKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKhoActionPerformed

    //Click vào nút tìm kiếm
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String id = txtTimKiem.getText();
        if (id.equals("")) {
            HienThiDanhSachDienThoai(dsdt);
        } else {
            HienThiTimKiem(id);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String id = txtMaDT.getText();
        XoaDienThoai(id);
        ClearTextbox();
        HienThiDanhSachDienThoai(dsdt);
        XoaDienThoaiCSDL(id);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCNActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCN;
    private java.awt.Button btnLoc;
    private java.awt.Button btnThemDienThoai;
    private java.awt.Button btnTimKiem;
    private java.awt.Button btnXoa;
    private java.awt.Button btnXuat;
    private javax.swing.JComboBox<String> cbxHang;
    private javax.swing.JComboBox<String> cbxKho;
    private javax.swing.JComboBox<String> cbxLoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTable tblDienThoai;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaDT;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtRom;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenDT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
