/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import forms.JPaneFormQLHoaDon;
/**
 *
 * @author tuananh
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelNav = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        btnQLDienThoai = new javax.swing.JButton();
        btnQLNhanVIen = new javax.swing.JButton();
        btnQLKhachHang = new javax.swing.JButton();
        btnQLHoaDon = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jPanelLogo1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 600));
        setSize(new java.awt.Dimension(1150, 600));
        getContentPane().setLayout(null);

        jPanelContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelContent.setLayout(null);
        getContentPane().add(jPanelContent);
        jPanelContent.setBounds(250, 0, 900, 600);
        jPanelContent.getAccessibleContext().setAccessibleParent(jPanelContent);

        jPanelNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelNav.setLayout(null);

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        jPanelNav.add(btnTrangChu);
        btnTrangChu.setBounds(0, 0, 250, 50);

        btnQLDienThoai.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQLDienThoai.setText("QL Điện Thoại");
        btnQLDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDienThoaiActionPerformed(evt);
            }
        });
        jPanelNav.add(btnQLDienThoai);
        btnQLDienThoai.setBounds(0, 50, 250, 50);

        btnQLNhanVIen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQLNhanVIen.setText("QL Nhân Viên");
        btnQLNhanVIen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVIenActionPerformed(evt);
            }
        });
        jPanelNav.add(btnQLNhanVIen);
        btnQLNhanVIen.setBounds(0, 100, 250, 50);

        btnQLKhachHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQLKhachHang.setText("QL Khách Hàng");
        jPanelNav.add(btnQLKhachHang);
        btnQLKhachHang.setBounds(0, 150, 250, 50);

        btnQLHoaDon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQLHoaDon.setText("QL Hóa Đơn");
        btnQLHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDonActionPerformed(evt);
            }
        });
        jPanelNav.add(btnQLHoaDon);
        btnQLHoaDon.setBounds(0, 200, 250, 50);

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThongKe.setText("Thống kê");
        jPanelNav.add(btnThongKe);
        btnThongKe.setBounds(0, 250, 250, 50);

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        jPanelNav.add(btnDangXuat);
        btnDangXuat.setBounds(0, 300, 250, 50);

        getContentPane().add(jPanelNav);
        jPanelNav.setBounds(0, 180, 250, 420);

        jPanelLogo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelLogo1.setLayout(null);
        getContentPane().add(jPanelLogo1);
        jPanelLogo1.setBounds(0, 0, 250, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDienThoaiActionPerformed
        jPanelContent.removeAll();
        
    }//GEN-LAST:event_btnQLDienThoaiActionPerformed

    private void btnQLHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDonActionPerformed
<<<<<<< HEAD
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDonActionPerformed

    private void btnQLNhanVIenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVIenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNhanVIenActionPerformed

=======
        JPaneFormQLHoaDon formHD = new JPaneFormQLHoaDon();
        jPanelContent.add(formHD);
        formHD.setSize(900, 600);
    }//GEN-LAST:event_btnQLHoaDonActionPerformed

>>>>>>> 02486b83e93a374c7912f6e247b003ce8346026e
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLDienThoai;
    private javax.swing.JButton btnQLHoaDon;
    private javax.swing.JButton btnQLKhachHang;
    private javax.swing.JButton btnQLNhanVIen;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelLogo1;
    private javax.swing.JPanel jPanelNav;
    // End of variables declaration//GEN-END:variables
}
